### ISSUE TITLE
Programatically setting form values on a conditionally hidden `sky-radio-group` produces error

### ISSUE THREAD

**Issue by blackbaud-joshlandi** [blackbaud/skyux-forms#32] opened 2019-04-15 17:13 UTC
### Expected behavior
If I use Reactive Forms I would expect to be able to set values programatically on the form, even if it's something that might get hidden. Using something like `this.form.get(key).setValue(value)`.

### Actual behavior

In the sample below I hide the element after selecting an option and when I do I get this error:
`ERROR Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges`

I wouldn't expect the component to believe the view has been destroyed (which it has, obviously).  I'd expect some sort of state tracking so I can maintain the radio button values whether hidden by angular or not.

### Steps to reproduce

Open : https://stackblitz.com/edit/angular-skyux-alert-demo-6xdl5c
Under "Reactive Form Setup" select a radio button.
Click "Hide".
Note error in console.

### Severity

- It's not a serious problem that many people will hit, i'd imagine.  But it's core to one of our forms and we'll need it.

### Impact

- We cannot release our addin-tile until this functionality is possible.  Unless a workaround is proposed.

**Comment by Blackbaud-AlexKingman** [comment] 2019-04-16 15:28
Thanks for submitting this @blackbaud-joshlandi . We'll do some internal team research on this and get back to you.

**Comment by blackbaud-joshlandi** [comment] 2019-08-12 12:08
@Blackbaud-AlexKingman has this been researched?  We hope to have our tile release by EOY.  If you all have already pinpointed the issue, I can offer to do the work.

**Comment by Blackbaud-AlexKingman** [comment] 2019-08-12 12:58
@blackbaud-joshlandi Thanks for checking in. No, work still needs to be done here. We'd love it if you're willing to make a contribution. Just let us know :)

**Comment by Blackbaud-TrevorBurch** [comment] 2019-10-03 19:01
Update: In 3.4.1 the view destroyed error is resolved. However, the value isn't being reset correctly. Looking into this.

**Comment by Blackbaud-TrevorBurch** [comment] 2019-10-03 19:24
Ok. @blackbaud-joshlandi I did some more digging and have figured out what is going on. With `3.4.1` you can get this to work. However, your Stackblitz resets the form to a value of a new object and does not use the same object as what the radio buttons are set up with. If you change your reset to use `this.seasons[3]` everything works because when the radio group tries to match values to the current group value it will equate as equal.

Closing this as I believe everything is working as intended in the component in version `3.4.1`

**Closed by Blackbaud-TrevorBurch** 2019-10-03 19:24 UTC
Labels: From: Consumer, Impact: Medium, Severity: High, Type: Bug
